# Sample playbook to patch and reboot the host servers
- name: Update and reboot
  # note: your 'hosts' section will likely be different as this is a group I created Amazon linux hosts in Ansible Tower itself.
  hosts: servers
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Upgrade all packages
      become: yes
      dnf:
        name: '*'
        state: latest
      
    - name: Reboot servers
      become: yes
      reboot:
        pre_reboot_delay: 90
        msg: "!!!Attention, server will be rebooted in 90 seconds!!!"
...
